// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
        int countGreaterThanHalf = 0;
        int countLessThanEqualHalf = 0;
        for (int i = 0; i < N; i++) {
            double randomValue = Math.random();
            if (randomValue > 0.5) {
                countGreaterThanHalf++;
            } else {
                countLessThanEqualHalf++;
            }
        }
        if (countLessThanEqualHalf == 0) {
            System.out.println("> 0.5: " + countGreaterThanHalf + " times");
            System.out.println("<= 0.5: " + countLessThanEqualHalf + " times");
            System.out.println("Ratio: Infinity");
        } else {
            double ratio = (double) countGreaterThanHalf / countLessThanEqualHalf;
            System.out.println("> 0.5: " + countGreaterThanHalf + " times");
            System.out.println("<= 0.5: " + countLessThanEqualHalf + " times");
            System.out.println("Ratio:" + ratio);
        }
    }
}   
